# Version of docker compose yaml file
version: '3.9'


services:
# MySQL Container
  mysql_db:
    image: mysql:8.0
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'wordpress'
      MYSQL_ROOT_PASSWORD: 'wordpress@123'
    ports:
      - '3306:3306'
    tty: true 
    restart: unless-stopped


# Wordpress Container Configurations
  wordpress_app:
    image: wordpress-env
    container_name: wordpress
    restart: unless-stopped
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./wordpress:/var/www/wordpress
      - ./nginx:/etc/nginx/sites-available
    ports:
      - "80:80"

# To connect with database 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1

    restart: always
    ports:
      - 8080:80

  # adminer:
  #   image: adminer
  #   environment:
  #     ADMINER_DEFAULT_SERVER: wordpress_app
  #   restart: always
  #   ports:
  #     - 8080:8080

volumes:
  mysql-volume:
